version: '3.3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pingcastle-mssql
    restart: unless-stopped
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pingcastle-net

  app:
    build: .
    container_name: pingcastle-app
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=db;Database=PingCastle;User Id=sa;Password=YourStrong!Passw0rd;
    volumes:
      - ./PingCastleEnterprise:/app
      - ./logs:/app/logs
    networks:
      - pingcastle-net

volumes:
  mssqldata:

networks:
  pingcastle-net:
